wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1633019122
    t:
      1:
      - 1
      - 5
      3:
      - 13
      4: 3.7.11
      5: 0.12.2
      8:
      - 1
      - 5
