wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    code_path: code/tools/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1632995759
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 13
      4: 3.7.11
      5: 0.12.2
      8:
      - 5
